  language: python
  python:
    - "3.5"
    - "3.6"
  branches:
    only:
      - master
  install:
    - pip install coveralls
    - pip install coverage
  script:
    - python setup.py install
    - coverage run test.py -v
  after_success:
    - coveralls
